# Generated by Django 5.1.2 on 2024-11-23 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hocapagehoca',
            name='page',
        ),
        migrations.RemoveField(
            model_name='hocapagehoca',
            name='hoca',
        ),
        migrations.DeleteModel(
            name='HocaPage',
        ),
        migrations.DeleteModel(
            name='HocaPageHoca',
        ),
    ]
