# Generated by Django 5.1.2 on 2024-11-25 12:42

import coderedcms.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_hocapage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customhomepage',
            name='about_us_section',
            field=coderedcms.fields.CoderedStreamField(blank=True, block_lookup={}),
        ),
        migrations.AddField(
            model_name='customhomepage',
            name='patient_journey_section',
            field=coderedcms.fields.CoderedStreamField(blank=True, block_lookup={}),
        ),
        migrations.AddField(
            model_name='customhomepage',
            name='portfolio_section',
            field=coderedcms.fields.CoderedStreamField(blank=True, block_lookup={}),
        ),
        migrations.AddField(
            model_name='customhomepage',
            name='pricing_section',
            field=coderedcms.fields.CoderedStreamField(blank=True, block_lookup={}),
        ),
        migrations.AddField(
            model_name='customhomepage',
            name='services_section',
            field=coderedcms.fields.CoderedStreamField(blank=True, block_lookup={}),
        ),
    ]
