# Generated by Django 5.1.2 on 2024-11-27 10:16

import coderedcms.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_localizedfooter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizedfooter',
            name='content',
            field=coderedcms.fields.CoderedStreamField(blank=True, block_lookup={}, verbose_name='Footer Content'),
        ),
    ]
