# Generated by Django 5.1.2 on 2024-11-27 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_footer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footer',
        ),
    ]
