# Generated by Django 5.1.2 on 2024-11-27 13:11

import coderedcms.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_delete_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterWithForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Footer Name')),
                ('content', coderedcms.fields.CoderedStreamField(block_lookup={}, verbose_name='Footer Content')),
                ('custom_css_class', models.CharField(blank=True, max_length=255, verbose_name='CSS Class')),
            ],
        ),
    ]
