# Generated by Django 5.1.2 on 2024-11-27 19:22

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_footerwithform'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='FAQ Title')),
                ('faqs', wagtail.fields.StreamField([('faq', 2)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Question', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Answer', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1)]], {'label': 'FAQ'})}, verbose_name='FAQs')),
            ],
            options={
                'verbose_name': 'FAQ Snippet',
                'verbose_name_plural': 'FAQ Snippets',
            },
        ),
    ]
