# Generated by Django 5.1.2 on 2024-11-27 23:42

import coderedcms.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaltourismpage',
            name='dentists_section',
            field=coderedcms.fields.CoderedStreamField(blank=True, block_lookup={}, verbose_name='Denrtists Section'),
        ),
    ]
