# Generated by Django 5.1.2 on 2024-11-28 18:00

import coderedcms.fields
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_medicaltourismpage_dentists_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTourismPagewithform',
            fields=[
                ('formpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.formpage')),
                ('hero_section', wagtail.fields.StreamField([('background_image', 0), ('title', 1), ('subtitle', 2), ('button_primary', 5), ('button_secondary', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Background Image'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Hero Title', 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Hero Subtitle', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Button Label', 'required': True}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'Button URL', 'required': True}), 5: ('wagtail.blocks.StructBlock', [[('label', 3), ('url', 4)]], {'label': 'Primary Button', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('label', 3), ('url', 4)]], {'label': 'Secondary Button', 'required': False})}, verbose_name='Hero Section')),
                ('about_section', wagtail.fields.StreamField([('image', 0), ('title', 1), ('subtitle', 2), ('text', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'About Image'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'About Title', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'About Subtitle', 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'label': 'About Description', 'required': False})}, verbose_name='About Section')),
                ('doctors_section', wagtail.fields.StreamField([('doctor', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Doctor Image'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Name', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Specialty', 'required': True}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Description', 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'Social/Profile Link', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('name', 1), ('specialty', 2), ('description', 3), ('social_link', 4)]], {'label': 'Doctor'})}, verbose_name='Doctors Section')),
                ('dentists_section', coderedcms.fields.CoderedStreamField(blank=True, block_lookup={}, verbose_name='Denrtists Section')),
                ('patient_journey_section', wagtail.fields.StreamField([('day', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Day Label', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Description', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('day_label', 0), ('description', 1)]], {'label': 'Patient Journey Day'})}, verbose_name='Patient Journey Section')),
                ('clinics_section', wagtail.fields.StreamField([('clinic', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Clinic Image'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Clinic Name', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Location', 'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'label': 'Description', 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'label': 'Google Maps Link', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('name', 1), ('location', 2), ('description', 3), ('map_link', 4)]], {'label': 'Clinic'})}, verbose_name='Clinics Section')),
                ('pricing_section', wagtail.fields.StreamField([('pricing_item', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Package Title', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Price', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Feature'}), 3: ('wagtail.blocks.ListBlock', (2,), {'label': 'Features List'}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Call to Action Label', 'required': True}), 5: ('wagtail.blocks.URLBlock', (), {'label': 'Call to Action URL', 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('price', 1), ('features', 3), ('cta_label', 4), ('cta_url', 5)]], {'label': 'Pricing Item'})}, verbose_name='Pricing Section')),
                ('faq_section', wagtail.fields.StreamField([('faq', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Question', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Answer', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1)]], {'label': 'FAQ'})}, verbose_name='FAQ Section')),
                ('gallery_section', wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Gallery Image'})}, verbose_name='Gallery Section')),
            ],
            options={
                'verbose_name': 'Medical Tourism Landing Page with form',
            },
            bases=('website.formpage',),
        ),
    ]
