# Generated by Django 5.1.2 on 2024-12-14 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_medicaltourismpagewithform'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebGLGalleryPage',
            fields=[
                ('formpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.formpage')),
            ],
            options={
                'verbose_name': 'webgl_gallery',
            },
            bases=('website.formpage',),
        ),
    ]
