# Generated by Django 5.1.2 on 2024-10-20 19:34

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderedcms', '0041_remove_layoutsettings_frontend_theme'),
        ('wagtail_word', '0002_remove_worddocumentpage_id_worddocumentpage_page_ptr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseWordDocumentPage',
            fields=[
                ('coderedpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coderedcms.coderedpage')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('author_display', models.CharField(blank=True, help_text='Override how the author’s name displays on this article.', max_length=255, verbose_name='Display author as')),
                ('date_display', models.DateField(blank=True, null=True, verbose_name='Display publish date')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('body', wagtail.fields.RichTextField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Word Document Article',
                'abstract': False,
            },
            bases=('coderedcms.coderedpage',),
        ),
        migrations.DeleteModel(
            name='WordDocumentPage',
        ),
    ]
