# Generated by Django 5.1.2 on 2024-10-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_word', '0003_baseworddocumentpage_delete_worddocumentpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseworddocumentpage',
            options={'verbose_name': 'Word Document or Blog Article'},
        ),
        migrations.AddField(
            model_name='baseworddocumentpage',
            name='blog_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
