# Generated by Django 5.1.2 on 2024-10-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_word', '0004_alter_baseworddocumentpage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseworddocumentpage',
            options={'verbose_name': 'Word Document Article'},
        ),
        migrations.RemoveField(
            model_name='baseworddocumentpage',
            name='blog_url',
        ),
    ]
