# Generated by Django 5.1.2 on 2024-12-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderedcms', '0041_remove_layoutsettings_frontend_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coderedpage',
            name='custom_template',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('coderedcms/pages/web_page.html', 'Web page showing title and cover image'), ('coderedcms/pages/web_page_notitle.html', 'Web page without title and cover image'), ('coderedcms/pages/home_page.html', 'Home page without title and cover image'), ('coderedcms/pages/base.html', 'Blank page - no navbar or footer')], max_length=255, verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='layoutsettings',
            name='navbar_collapse_mode',
            field=models.CharField(blank=True, choices=[('', 'Never show menu - Always collapse menu behind a button'), ('navbar-expand-sm', 'sm - Show on small screens (phone size) and larger'), ('navbar-expand-md', 'md - Show on medium screens (tablet size) and larger'), ('navbar-expand-lg', 'lg - Show on large screens (laptop size) and larger'), ('navbar-expand-xl', 'xl - Show on extra large screens (desktop, wide monitor)')], default='', help_text='Control on what screen sizes to show and collapse the navbar menu links.', max_length=50, verbose_name='Collapse navbar menu'),
        ),
        migrations.AlterField(
            model_name='layoutsettings',
            name='navbar_color_scheme',
            field=models.CharField(blank=True, choices=[('navbar-light', 'Light - for use with a light-colored navbar'), ('navbar-dark', 'Dark - for use with a dark-colored navbar')], default='', help_text='Optimizes text and other navbar elements for use with light or dark backgrounds.', max_length=50, verbose_name='Navbar color scheme'),
        ),
        migrations.AlterField(
            model_name='layoutsettings',
            name='navbar_format',
            field=models.CharField(blank=True, choices=[('', 'Default Bootstrap Navbar'), ('crx-navbar-center', 'Centered logo at top')], default='', max_length=50, verbose_name='Navbar format'),
        ),
    ]
