# Generated by Django 5.1.2 on 2024-12-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderedcms', '0042_alter_coderedpage_custom_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coderedpage',
            name='custom_template',
            field=models.CharField(blank=True, max_length=255, verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='layoutsettings',
            name='navbar_collapse_mode',
            field=models.CharField(blank=True, default='', help_text='Control on what screen sizes to show and collapse the navbar menu links.', max_length=50, verbose_name='Collapse navbar menu'),
        ),
        migrations.AlterField(
            model_name='layoutsettings',
            name='navbar_color_scheme',
            field=models.CharField(blank=True, default='', help_text='Optimizes text and other navbar elements for use with light or dark backgrounds.', max_length=50, verbose_name='Navbar color scheme'),
        ),
        migrations.AlterField(
            model_name='layoutsettings',
            name='navbar_format',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Navbar format'),
        ),
    ]
