# Generated by Django 5.1.2 on 2024-11-20 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_doctor_locale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
