# Generated by Django 5.1.2 on 2024-11-22 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_customarticlepage_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hocapage',
            name='featured_hoca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_on_pages', to='website.hoca'),
        ),
    ]
